PIN-383: assistances
humansis/api pull request #223
Opened 2020-09-29 14:16 UTC by Troi

2020-09-29 14:52 UTC, iarro requested changes

2020-09-29 14:52 UTC, iarro commented on src/DistributionBundle/Entity/Assistance.php
>   * @ORM\Table(name="distribution_data")
Why table is not renamed?

2020-10-01 12:48 UTC, Troi commented on src/DistributionBundle/Entity/Assistance.php
>   * @ORM\Table(name="distribution_data")
renamed and will be rebased

2020-10-01 12:48 UTC, Troi commented
will be rebased

2020-10-01 12:48 UTC, closed without merging