PIN-540: smartcard redemption
humansis/api pull request #227
Opened 2020-10-05 14:35 UTC by Troi

2020-10-06 08:55 UTC, iarro requested changes

2020-10-06 08:55 UTC, iarro commented on src/VoucherBundle/Controller/VendorController.php
> +     * @Rest\Get("/vendors/{id}/purchases", name="get_all_vendor_purchases")
Wrong enpoint name. You return only smartcard purchases, not ALL purchases. It should be defined in /smartcards

2020-10-06 08:55 UTC, iarro commented on src/VoucherBundle/Controller/VendorController.php
> +     * @Rest\Get("/vendors/{id}/purchases", name="get_all_vendor_purchases")
All added functionality should be in SmartcardController

2020-10-06 08:55 UTC, iarro commented on src/VoucherBundle/Controller/VendorController.php
> +     * @Rest\Get("/vendors/{id}/purchases", name="get_all_vendor_purchases")
Also, are there urls accesible by mobile app. In that case, it shoult be prefixed by vendor-app or offline-app

2020-10-07 10:39 UTC, Troi commented on src/VoucherBundle/Controller/VendorController.php
> +     * @Rest\Get("/vendors/{id}/purchases", name="get_all_vendor_purchases")
updated

mobile apps arent consumer of this endpoints

2020-10-07 10:40 UTC, Troi commented
will be rebased

2020-10-07 10:40 UTC, closed without merging