PIN-559: sector migration bug
humansis/api pull request #230
Opened 2020-10-06 15:28 UTC by Troi

2020-10-08 15:39 UTC, iarro requested changes

2020-10-08 15:39 UTC, iarro commented on app/DoctrineMigrations/Version20200814092226.php
> +        $this->addSql('CREATE UNIQUE INDEX uniq_sector_project ON project_sector (sector, subsector, project_id)');
I dont understand why you drop index and after that you create it again. If you edit exists migration you cant do it.
Also, uniq_sector_project index is defined in ProjectSector entity, so you should make it sync with that

2020-10-11 11:37 UTC, Troi commented on app/DoctrineMigrations/Version20200814092226.php
> +        $this->addSql('CREATE UNIQUE INDEX uniq_sector_project ON project_sector (sector, subsector, project_id)');
Reason is the old unique constraint is on two columns only and should be on three and I dont know way how to add column to unique constraint.

But update ProjectSector is missing.

2020-10-12 09:54 UTC, iarro approved these changes

2020-10-12 11:16 UTC, merged