PIN-437: Vulnereability scoring feature
humansis/api pull request #247
Opened 2020-10-16 10:07 UTC by pavlix98

2020-10-19 07:35 UTC, Troi requested changes
There are some minor requests but it looks good

2020-10-19 07:35 UTC, Troi commented on src/BeneficiaryBundle/Model/Vulnerability/Resolver.php
> +                return 0; //TODO is it ok?
Yes, it little weird construction but ok

2020-10-19 07:35 UTC, Troi commented on src/BeneficiaryBundle/Model/Vulnerability/ScoringParser.php
> +    public function processCsv(array $csv): object
if you dont need to use it outside and dont test it then it shouldn't be public but protected.

2020-10-19 07:35 UTC, Troi commented on src/ProjectBundle/Resources/config/services.yml
> +        arguments: []
it isnt necessary

2020-10-19 07:35 UTC, Troi commented on tests/BeneficiaryBundle/Model/Vulnerability/ResolverTest.php
> +            'highVulnerability' => [800, 1000, 4],
note: this isnt id, it is only description text, so you can use standard test formatting

2020-10-21 14:27 UTC, pavlix98 commented on src/ProjectBundle/Resources/config/services.yml
> +        arguments: []
I think this is your change, I am not sure why it is part of vulnerability pull request.

2020-10-22 10:56 UTC, Troi commented on src/ProjectBundle/Resources/config/services.yml
> +        arguments: []
oh, you're right. so it doesnt matter now

2020-10-23 06:46 UTC, Troi approved these changes

2020-10-26 13:22 UTC, merged