PIN-665: Dependency ratio vulnerability
humansis/api pull request #257
Opened 2020-10-22 18:26 UTC by pavlix98

Please merge this pull request AFTER resolving this pull request: 
https://github.com/humansis/api/pull/247

2020-10-23 06:40 UTC, Troi requested changes
i think there are logic mistakes to fix

2020-10-23 06:40 UTC, Troi commented on tests/BeneficiaryBundle/Model/Vulnerability/ResolverTest.php
> +        $this->assertEquals(6, $protocol->getCategoryScore(CategoryEnum::DEPENDENCY_RATIO));
Empty HH without HHH and any members should have dependency 6? It sounds like mistake.

2020-10-23 06:40 UTC, Troi commented on tests/BeneficiaryBundle/Model/Vulnerability/ResolverTest.php
> +        $this->assertEquals(1, $protocol->getCategoryScore(CategoryEnum::DEPENDENCY_RATIO));
This is mistake: one productive adult should have dependency ratio = zero.

2020-10-23 06:40 UTC, Troi commented on tests/BeneficiaryBundle/Model/Vulnerability/ResolverTest.php
> +        $this->assertEquals(4, $protocol->getCategoryScore(CategoryEnum::DEPENDENCY_RATIO));
Test adding more productive adults and lowering ratio.

2020-10-23 06:40 UTC, Troi commented on src/BeneficiaryBundle/Model/Vulnerability/Resolver.php
>          if ($adults === 0) {
make branch for no BNF

2020-10-25 20:38 UTC, pavlix98 commented on tests/BeneficiaryBundle/Model/Vulnerability/ResolverTest.php
> +        $this->assertEquals(1, $protocol->getCategoryScore(CategoryEnum::DEPENDENCY_RATIO));
I think this is actually true: Yes, the dependecy ration will be 0 (because the formula will be 0/1 = 0 ), so the depency is in interval <0, 1> and this interval has score value 1  for testing (you can check score values [here](https://github.com/humansis/api/blob/quanti/pin-437-vulnerability2/tests/BeneficiaryBundle/Resources/Vulnerability/resolver_scoring_SYR.csv)).

2020-11-02 08:11 UTC, Troi approved these changes

2020-11-05 09:45 UTC, merged