PIN-656: Vulnerability household members
humansis/api pull request #262
Opened 2020-10-27 09:30 UTC by pavlix98

Please merge this pull request AFTER resolving this pull request:
https://github.com/humansis/api/pull/257

2020-10-27 10:09 UTC, Troi requested changes
only minor update

2020-10-27 10:09 UTC, Troi commented on src/BeneficiaryBundle/Model/Vulnerability/Resolver.php
> +            if ($member->getAge() !== null && $member->getAge() < self::AGE_LIMIT_INFANT) {
Child age missing

2020-11-01 18:51 UTC, pavlix98 commented on src/BeneficiaryBundle/Model/Vulnerability/Resolver.php
> +            if ($member->getAge() !== null && $member->getAge() < self::AGE_LIMIT_INFANT) {
There actually should be only infant. Fixed.

2020-11-02 08:22 UTC, Troi approved these changes

2020-11-05 09:45 UTC, merged