PIN-762: smarcard batch
humansis/api pull request #284
Opened 2020-11-09 12:53 UTC by Troi

2020-11-10 07:06 UTC, iarro requested changes

2020-11-10 07:06 UTC, iarro commented on src/VoucherBundle/Controller/SmartcardController.php
> +     * @Rest\Get("/smartcards/purchases/redeemed-batches/{id}/batch-details/{batchDate}", name="smarcards_redeemed_batches_details")
Im not sure is good idea to have filtering in url path. It will be hard to extends this enpoint.
IMHO is better idea to have this filter in query param, like this `?batchDate=12345678`

2020-11-10 07:06 UTC, iarro commented on src/VoucherBundle/Repository/SmartcardPurchaseRepository.php
> +            ->andWhere('p.redeemedAt = :batch')
Shouldnt be here some kind of range to filter by time? Something like `... WHERE p.redeemedAt BETWEEN date1 AND date 2 ...`

2020-11-12 08:43 UTC, Troi commented on src/VoucherBundle/Repository/SmartcardPurchaseRepository.php
> +            ->andWhere('p.redeemedAt = :batch')
it shouldnt, batches are defined by exactly same time so range could take more redemption batches together

2020-11-12 08:55 UTC, Troi commented on src/VoucherBundle/Controller/SmartcardController.php
> +     * @Rest\Get("/smartcards/purchases/redeemed-batches/{id}/batch-details/{batchDate}", name="smarcards_redeemed_batches_details")
It isnt actually filtering, date is something like ID for batches, so I think it should be in URL if endpoint doesnt have meaning without this parameter

2020-11-12 18:13 UTC, closed without merging