PIN-1097: Vendors endpoints
humansis/api pull request #395
Opened 2020-12-15 12:35 UTC by pavlix98

2020-12-17 06:33 UTC, iarro requested changes

2020-12-17 06:33 UTC, iarro commented on src/NewApiBundle/InputType/VendorCreateInputType.php
> +     * @return mixed
Please add type into php doc block.

Also, there are inconsistences in getters/setters. At first, you declare only getters, then only setters, and for one property you declare getter and setter behind you. It's confusing

2020-12-17 06:33 UTC, iarro commented on src/NewApiBundle/InputType/VendorOrderInputType.php
> +}
Missing newline

2020-12-17 06:33 UTC, iarro commented on src/NewApiBundle/InputType/VendorUpdateInputType.php
> +    /**
same problem as above

2020-12-17 06:33 UTC, iarro commented on src/NewApiBundle/Mapper/VendorMapper.php
> +    public function getLocationId(): ?int
location is required. It cannot be nullable

2020-12-17 06:33 UTC, iarro commented on src/VoucherBundle/Utils/VendorService.php
> +        if (!($location instanceof Location)) {
inner brackets are not necessary if (!$location instanceof Location)  works fine

2020-12-17 14:03 UTC, pavlix98 commented on src/NewApiBundle/Mapper/VendorMapper.php
> +    public function getLocationId(): ?int
Location definitely should be required, but column "location_id" in table "vendor" is nullable, so this could possibly return null.

2020-12-17 21:39 UTC, iarro commented on src/NewApiBundle/Mapper/VendorMapper.php
> +    public function getLocationId(): ?int
you are right but I think it is just mistake. There is no vendor without location in DB. Also, FE creation form requires at least one location to choose.

2020-12-21 11:04 UTC, pavlix98 commented on src/NewApiBundle/Mapper/VendorMapper.php
> +    public function getLocationId(): ?int
okay, we should fix this from bottom then. I would change the column to required.

2021-01-18 13:41 UTC, merged